Market/Market/Models/Supplier.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Market.Models
{
    public partial class Supplier
    {
        public Supplier()
        {
            Products = new HashSet<Product>();
        }
        [Required(ErrorMessage = "Mã nhà cung cấp không được để trống!")]
        [DisplayName("Mã nhà cung cấp")]
        public string SupplierId { get; set; } = null!;

        [Required(ErrorMessage = "Tên nhà cung cấp không được để trống!")]
        [DisplayName("Tên nhà cung cấp")]
        public string? SupplierName { get; set; }

        [Required(ErrorMessage = "Địa chỉ nhà cung cấp không được để trống!")]
        [DisplayName("Địa chỉ")]
        public string? Address { get; set; }

        [Required(ErrorMessage = "SĐT nhà cung cấp không được để trống!")]
        [RegularExpression(@"^\d{10}$", ErrorMessage = "Số điện thoại phải có 10 chữ số")]
        [DisplayName("Số điện thoại")]
        public string? Phone { get; set; }

        [Required(ErrorMessage = "Trạng thái không được để trống!")]
        [DisplayName("Trạng thái")]
        public int? Status { get; set; }

        public virtual ICollection<Product> Products { get; set; }
    }
}

Market/Market/Areas/Admin/Controllers/SuppliersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Market.Models;
using Market.Areas.Admin.Helpers;

namespace Market.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class SuppliersController : Controller
    {
        private readonly MarketContext _context;

        public SuppliersController(MarketContext context)
        {
            _context = context;
        }

        // GET: Admin/Suppliers
        private int pageSize = 3;
        [Route("Admin/Suppliers/Index")]
        public async Task<IActionResult> Index(int? s)
        {
            var suppliers = (IQueryable<Supplier>)_context.Suppliers;

            if (s != null)
            {
                suppliers = (IQueryable<Supplier>)_context.Suppliers.Where(c => c.Status == s);
            }
            // tính số trang 
            int pageNum = (int)Math.Ceiling(suppliers.Count() / (float)pageSize);

            // trả số trang về view để hiển thị nav-trang
            ViewBag.pageNum = pageNum;

            //lấy dữ liệu trang đầu
            var result = suppliers.Take(pageSize).ToList();

            List<SelectListItem> listStatus = CategoryStatusHelper.GetStatusList();
            ViewBag.Status = listStatus;

            return View(result);

        }


        public IActionResult SupplierFilter(int? s, string? keyword, int? pageIndex)
        {
            var suppliers = (IQueryable<Supplier>)_context.Suppliers;

            // lấy chỉ số trang
            int page = (int)(pageIndex == null || pageIndex <= 0 ? 1 : pageIndex);

            if (s != null && s != 0)
            {
                //lọc
                suppliers = suppliers.Where(c => c.Status == s);

                // gửi s về view để ghi lại trên nav-phân trang
                ViewBag.s = s;
            }

            if (keyword != null && keyword != "")
            {
                suppliers = suppliers.Where(x => x.SupplierId.ToLower().Contains(keyword.ToLower()) ||
                                                x.SupplierName.ToLower().Contains(keyword.ToLower()));
                ViewBag.keyword = keyword;
            }

            // tính số trang 
            int pageNum = (int)Math.Ceiling(suppliers.Count() / (float)pageSize);

            // gửi về view
            ViewBag.pageNum = pageNum;

            // chọn dữ liệu trong trang hiện tại 
            var result = suppliers.Skip(pageSize * (page - 1)).Take(pageSize);

            return PartialView("SupplierTable", result);
        } // GET: Admin/Suppliers/Details/5


        // GET: Admin/Suppliers/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Admin/Suppliers/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("SupplierId,SupplierName,Address,Phone,Status")] Supplier supplier)
        {
            if (ModelState.IsValid)
            {
                _context.Add(supplier);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(supplier);
        }

        // GET: Admin/Suppliers/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.Suppliers == null)
            {
                return NotFound();
            }

            var supplier = await _context.Suppliers.FindAsync(id);
            if (supplier == null)
            {
                return NotFound();
            }
            return View(supplier);
        }

        // POST: Admin/Suppliers/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("SupplierId,SupplierName,Address,Phone,Status")] Supplier supplier)
        {
            if (id != supplier.SupplierId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(supplier);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!SupplierExists(supplier.SupplierId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(supplier);
        }
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.Suppliers == null)
            {
                return NotFound();
            }

            var supplier = await _context.Suppliers
                .FirstOrDefaultAsync(m => m.SupplierId == id);
            if (supplier == null)
            {
                return NotFound();
            }

            return View(supplier);
        }
        // GET: Admin/Suppliers/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null || _context.Suppliers == null)
            {
                return NotFound();
            }

            var supplier = await _context.Suppliers
                .FirstOrDefaultAsync(m => m.SupplierId == id);
            if (supplier == null)
            {
                return NotFound();
            }

            return View(supplier);
        }

        // POST: Admin/Suppliers/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (_context.Suppliers == null)
            {
                return Problem("Entity set 'MarketContext.Suppliers'  is null.");
            }
            var supplier = await _context.Suppliers.FindAsync(id);
            if (supplier != null)
            {
                _context.Suppliers.Remove(supplier);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool SupplierExists(string id)
        {
            return (_context.Suppliers?.Any(e => e.SupplierId == id)).GetValueOrDefault();
        }
    }
}

Market/Market/Areas/Admin/Views/Suppliers/Create.cshtml
@model Market.Models.Supplier

@{
    ViewData["Title"] = "Thêm nhà cung cấp";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Create</h1>

<h4>Supplier</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="SupplierId" class="control-label"></label>
                <input asp-for="SupplierId" class="form-control" />
                <span asp-validation-for="SupplierId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SupplierName" class="control-label"></label>
                <input asp-for="SupplierName" class="form-control" />
                <span asp-validation-for="SupplierName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

Market/Market/Areas/Admin/Views/Suppliers/Delete.cshtml
@model Market.Models.Supplier

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Supplier</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SupplierName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SupplierName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="SupplierId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Market/Market/Areas/Admin/Views/Suppliers/Details.cshtml
@model Market.Models.Supplier

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Supplier</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.SupplierName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.SupplierName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Address)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Address)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Phone)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Phone)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.SupplierId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Market/Market/Areas/Admin/Views/Suppliers/Edit.cshtml
@model Market.Models.Supplier

@{
    ViewData["Title"] = "Sửa nhà cung cấp";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Edit</h1>

<h4>Supplier</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="SupplierId" />
            <div class="form-group">
                <label asp-for="SupplierName" class="control-label"></label>
                <input asp-for="SupplierName" class="form-control" />
                <span asp-validation-for="SupplierName" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Address" class="control-label"></label>
                <input asp-for="Address" class="form-control" />
                <span asp-validation-for="Address" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Phone" class="control-label"></label>
                <input asp-for="Phone" class="form-control" />
                <span asp-validation-for="Phone" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@* @section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
} *@

Market/Market/Areas/Admin/Views/Suppliers/Index.cshtml
@model IEnumerable<Market.Models.Supplier>

@{
    ViewData["Title"] = "Danh sách nhà cung cấp";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">
    <h2 class="header-title" style="font-size: 24px">Danh sách nhà cung cấp </h2>
</div>
<div class="card">
    <div class="card-body">
        <div class="row m-b-30">
            <div class="col-lg-8">
                <div class=" col-lg-5 m-b-10">
                    <select class="custom-select" id="sltStatus" name="sltStatus" asp-items="@ViewBag.Status" style="min-width: 180px;">
                        <option selected disabled>Trạng thái</option>
                        <option value="0">Tất cả</option>
                    </select>
                </div>
            </div>

            <div class=" col-lg-4 text-right">
                <a class="btn btn-primary m-l-5" asp-area="Admin" asp-controller="Suppliers" asp-action="Create">
                    <i class="anticon anticon-plus-circle m-r-5"></i>
                    <span>Thêm nhà cung cấp</span>
                </a>
            </div>
        </div>


        <div class="row m-b-20">
            <div class="col-sm-6">
                <div class="input-group">
                    <input id="keyword" name="keyword" type="text" class="form-control" placeholder="Tìm kiếm nhà cung cấp">
                    <button id="btnSearch" class="btn btn-primary m-l-5" type="button"><i class="anticon anticon-search"></i> Tìm kiếm</button>
                </div>
            </div>
            <div class="col-md-6">
                <button id="btnRefresh" class="btn btn-success m-r-5"><i class="anticon anticon-reload"></i> Làm mới</button>
            </div>
        </div>

        <div class="row" id="content">
            <div class="col-sm-12 table-responsive">
                <table class="table table-hover e-commerce-table" style="border-collapse: collapse; border-spacing: 20px;">
                    <thead>
                        <tr class="text-center">
                            <th class="text-nowrap">Mã nhà cung cấp</th>
                            <th class="text-nowrap">Tên nhà cung cấp</th>
                            <th class="text-nowrap">Địa chỉ</th>
                            <th class="text-nowrap">Số điện thoại</th>
                            <th class="text-nowrap">Trạng thái</th>
                            <th class="text-nowrap">Chức năng</th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (var item in Model)
                        {
                            <tr class="text-center">
                                <td>
                                    @item.SupplierId
                                </td>
                                <td>
                                    @item.SupplierName
                                </td>

                                <td>
                                    @item.Address
                                </td>
                                <td>
                                    @item.Phone
                                </td>

                                <td>
                                    @*  @item.StatusString *@
                                    @if (item.Status == 1)
                                    {
                                        <div>
                                            <div class="badge badge-success badge-dot m-r-10"></div>
                                            <span>Đang hợp tác</span>
                                        </div>
                                    }
                                    else if (item.Status == 2)
                                    {
                                        <div>
                                            <div class="badge badge-danger badge-dot m-r-10"></div>
                                            <span>Ngừng hợp tác</span>
                                        </div>
                                    }
                                </td>

                                <td>
                                    <a class="btn btn-icon btn-hover btn-sm btn-rounded pull-right" asp-area="Admin" asp-controller="Suppliers" asp-action="Edit" asp-route-id="@item.SupplierId"><i class="anticon anticon-edit"></i></a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>

            </div>
            @* Thanh nav-phân trang *@
            <ul class="pagination m-l-20 m-t-5">
                @for (int i = 1; i <= ViewBag.pageNum; i++)
                {
                    <li class="page-item active" page="@i"
                    @(ViewBag.s != null ? " s='@ViewBag.s'" : "")
                    @(ViewBag.keyword != null ? " keyword='@ViewBag.keyword'" : "")>
                        <a class="page-link" style="border-radius: 5px;">@i</a>
                    </li>
                }
            </ul>
        </div>
    </div>
</div>
@section Scripts{
    <script>
        $('body').on('click', 'li.page-item', function (e) {
            var page = $(this).attr("page");
            var s = $(this).attr("s");
            var keyword = $(this).attr("keyword");
            var data = { s: s, keyword: keyword, pageIndex: page };
            $.ajax({
                url: "SupplierFilter",
                data: data,
                success: function (response) {
                    $("div#content").html(response);
                }
            });
        });

        $("select#sltStatus").change(function (e) {
            var status = $("#sltStatus").val();
            var keyword = $("#keyword").val();
            var data = { s: status, keyword: keyword };
            $.ajax({
                url: "SupplierFilter",
                data: data,
                success: function (response) {
                    $("div#content").html(response);
                }
            });
        });
        $("button#btnSearch").click(function (e) {
            var status = $("#sltStatus").val();
            var keyword = $("#keyword").val();
            var data = { s: status, keyword: keyword };
            $.ajax({
                url: "SupplierFilter",
                data: data,
                success: function (response) {
                    $("div#content").html(response);
                }
            });
        });
        $("#btnRefresh").click(function () {
            window.location.href = '/Admin/Suppliers/Index';
        });
    </script>
}

Market/Market/Areas/Admin/Views/Suppliers/SupplierTable.cshtml
@model IEnumerable<Market.Models.Supplier>
<div class="col-sm-12 table-responsive">
    <table class="table table-hover e-commerce-table" style="border-collapse: collapse; border-spacing: 20px;">
        <thead>
            <tr class="text-center">
                <th class="text-nowrap">Mã nhà cung cấp</th>
                <th class="text-nowrap">Tên nhà cung cấp</th>
                <th class="text-nowrap">Địa chỉ</th>
                <th class="text-nowrap">Số điện thoại</th>
                <th class="text-nowrap">Trạng thái</th>
                <th class="text-nowrap">Chức năng</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr class="text-center">
                    <td>
                        @item.SupplierId
                    </td>
                    <td>
                        @item.SupplierName
                    </td>

                    <td>
                        @item.Address
                    </td>
                    <td>
                        @item.Phone
                    </td>

                    <td>
                        @*  @item.StatusString *@
                        @if (item.Status == 1)
                        {
                            <div>
                                <div class="badge badge-success badge-dot m-r-10"></div>
                                <span>Đang hợp tác</span>
                            </div>
                        }
                        else if (item.Status == 2)
                        {
                            <div>
                                <div class="badge badge-danger badge-dot m-r-10"></div>
                                <span>Ngừng hợp tác</span>
                            </div>
                        }
                    </td>

                    <td>
                        <a class="btn btn-icon btn-hover btn-sm btn-rounded pull-right" asp-area="Admin" asp-controller="Suppliers" asp-action="Edit" asp-route-id="@item.SupplierId"><i class="anticon anticon-edit"></i></a>
                    </td>
                </tr>
            }
        </tbody>
    </table>

</div>
@* Thanh nav-phân trang *@
<ul class="pagination m-l-20 m-t-5">
    @for (int i = 1; i <= ViewBag.pageNum; i++)
    {
        <li class="page-item active" page="@i"
        @(ViewBag.s != null ? " s='@ViewBag.s'" : "")
        @(ViewBag.keyword != null ? " keyword='@ViewBag.keyword'" : "")>
            <a class="page-link" style="border-radius: 5px;">@i</a>
        </li>
    }
</ul>