Market/Market/Areas/Admin/Controllers/AdminOrderDetailsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Market.Models;
using AspNetCoreHero.ToastNotification.Abstractions;
using Microsoft.CodeAnalysis;
using PayPal.Api;

namespace Market.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class AdminOrderDetailsController : Controller
    {
        private readonly MarketContext _context;
        public INotyfService _notyfService { get; }

        public AdminOrderDetailsController(MarketContext context, INotyfService notyfService)
        {
            _context = context;
            _notyfService = notyfService;
        }

        public async Task<IActionResult> Index(string id)
        {
            if (id == null)
            {
                return NotFound();
            }
            var order = await _context.Orders.FirstOrDefaultAsync(o => o.OrderId == id);

            if (order == null)
            {
                return NotFound();
            }
            var orderDetail = await _context.OrderDetails
                .Include(o => o.Order)
                .Include(o => o.Product)
                .Where(od => od.OrderId == id)
                .ToListAsync();
            if (orderDetail == null)
            {               
                ViewBag.Order = order;
                return View();
            }
            ViewBag.Order = order;
            return View(orderDetail);
        }
        public IActionResult Create(string orderID)
        {
            ViewData["OrderId"] = new SelectList(_context.Orders, "OrderId", "OrderId", orderID);
            ViewData["ProductId"] = new SelectList(_context.Products, "ProductId", "ProductName");
            var orderDetail = new OrderDetail();
            if (!string.IsNullOrEmpty(orderID))
            {
                orderDetail.OrderId = orderID;
            }

            return View(orderDetail);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("OrderId,ProductId,Price,Amount,Sale,Total")] OrderDetail orderDetail)
        {
            if (ModelState.IsValid)
            {
                _context.Add(orderDetail);
                await _context.SaveChangesAsync();
                _notyfService.Success("Thêm sản phẩm thành công !");
                return RedirectToAction("Index", new { id = orderDetail.OrderId });
                
            }
            ViewData["OrderId"] = new SelectList(_context.Orders, "OrderId", "OrderId", orderDetail.OrderId);
            ViewData["ProductId"] = new SelectList(_context.Products, "ProductId", "ProductName", orderDetail.ProductId);

            return View(orderDetail);
        }

        public async Task<IActionResult> Edit(string orderID, string productID)
        {
            if (orderID == null || productID == null)
            {
                return NotFound();
            }

            var orderDetail = await _context.OrderDetails
                .AsNoTracking()
                .FirstOrDefaultAsync(m => m.OrderId == orderID && m.ProductId == productID);

            if (orderDetail == null)
            {
                return NotFound();
            }

            ViewData["OrderId"] = new SelectList(_context.Orders, "OrderId", "OrderId", orderDetail.OrderId);
            ViewData["ProductId"] = new SelectList(_context.Products, "ProductId", "ProductId", orderDetail.ProductId);

            return View(orderDetail);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string orderID, string productID, [Bind("OrderId,ProductId,Price,Amount,Sale,Total")] OrderDetail orderDetail)
        {
            if (orderID != orderDetail.OrderId || productID != orderDetail.ProductId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(orderDetail);
                    await _context.SaveChangesAsync();

                    _notyfService.Success("Cập nhật thành công");
                    return RedirectToAction("Index", new { id = orderID });
                }
                catch (DbUpdateConcurrencyException ex)
                {
                    if (!OrderDetailExists(orderDetail.OrderId, orderDetail.ProductId))
                    {
                        return NotFound();
                    }
                }
            }

            ViewData["OrderId"] = new SelectList(_context.Orders, "OrderId", "OrderId", orderDetail.OrderId);
            ViewData["ProductId"] = new SelectList(_context.Products, "ProductId", "ProductId", orderDetail.ProductId);
            return View(orderDetail);
        }

        public async Task<IActionResult> Delete(string orderID, string productID)
        {
            if (orderID == null || productID == null || _context.OrderDetails == null)
            {
                return NotFound();
            }

			var orderDetail = await _context.OrderDetails
		        .Include(o => o.Order)
		        .Include(o => o.Product)
		        .FirstOrDefaultAsync(m => m.OrderId == orderID && m.ProductId == productID);
			if (orderDetail == null)
            {
                return NotFound();
            }

            return View(orderDetail);
        }
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string orderID, string productID)
        {
            if (_context.OrderDetails == null)
            {
                return Problem("Entity set 'MarketContext.OrderDetails'  is null.");
            }
			var orderDetail = await _context.OrderDetails
		     .FirstOrDefaultAsync(m => m.OrderId == orderID && m.ProductId == productID); 
			if (orderDetail != null)
            {
                _context.OrderDetails.Remove(orderDetail);
                await _context.SaveChangesAsync();
				_notyfService.Success("Xóa sản phẩm thành công !");
				return RedirectToAction("Index", new { id = orderID });
            }

            return NotFound();
        }

        private bool OrderDetailExists(string orderId, string productId)
        {
            return (_context.OrderDetails?.Any(e => e.OrderId == orderId && e.ProductId == productId)).GetValueOrDefault();
        }
    }
}

Market/Market/Areas/Admin/Views/AdminOrderDetails/Create.cshtml
@model Market.Models.OrderDetail

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Create</h1>

<h4>OrderDetail</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="OrderId" class="control-label"></label>
                <select asp-for="OrderId" class ="form-control" asp-items="ViewBag.OrderId"></select>
            </div>
            <div class="form-group">
                <label asp-for="ProductId" class="control-label"></label>
                <select asp-for="ProductId" class ="form-control" asp-items="ViewBag.ProductId"></select>
            </div>
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Amount" class="control-label"></label>
                <input asp-for="Amount" class="form-control" />
                <span asp-validation-for="Amount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sale" class="control-label"></label>
                <input asp-for="Sale" class="form-control" />
                <span asp-validation-for="Sale" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Total" class="control-label"></label>
                <input asp-for="Total" class="form-control" />
                <span asp-validation-for="Total" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-secondary btn-tone" asp-area="Admin" asp-controller="AdminOrders" asp-action="Index">
        <i class="anticon anticon-arrow-left m-r-5"></i>
        <span>Quay lại</span>
    </a>
</div>

Market/Market/Areas/Admin/Views/AdminOrderDetails/Delete.cshtml
@model Market.Models.OrderDetail

@{
    ViewData["Title"] = "Delete";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>OrderDetail</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Price)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Price)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Amount)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Amount)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Sale)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Sale)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Total)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Total)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Order)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Order.OrderId)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Product)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Product.ProductId)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="OrderId" />
        <input type="hidden" asp-for="ProductId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a class="btn btn-secondary btn-tone" asp-area="Admin" asp-controller="AdminOrders" asp-action="Index">
            <i class="anticon anticon-arrow-left m-r-5"></i>
            <span>Quay lại</span>
        </a>
    </form>
</div>

Market/Market/Areas/Admin/Views/AdminOrderDetails/Edit.cshtml
@model Market.Models.OrderDetail

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<h1>Chỉnh sửa chi tiết hóa đơn</h1>

<h4>OrderDetail</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="OrderId" />
            <input type="hidden" asp-for="ProductId" />
            <div class="form-group">
                <label asp-for="Price" class="control-label"></label>
                <input asp-for="Price" class="form-control" />
                <span asp-validation-for="Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Amount" class="control-label"></label>
                <input asp-for="Amount" class="form-control" />
                <span asp-validation-for="Amount" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Sale" class="control-label"></label>
                <input asp-for="Sale" class="form-control" />
                <span asp-validation-for="Sale" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Total" class="control-label"></label>
                <input asp-for="Total" class="form-control" />
                <span asp-validation-for="Total" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a class="btn btn-secondary btn-tone" asp-area="Admin" asp-controller="AdminOrders" asp-action="Index">
        <i class="anticon anticon-arrow-left m-r-5"></i>
        <span>Quay lại</span>
    </a>
</div>

Market/Market/Areas/Admin/Views/AdminOrderDetails/Index.cshtml
@model IEnumerable<Market.Models.OrderDetail>

@{
    ViewData["Title"] = "Index";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">
    <h2 class="header-title"></h2>
    <div class="header-sub-title">
        <nav class="breadcrumb breadcrumb-dash">
            <a asp-area="Admin" asp-controller="AdminOrders" asp-action="Home" class="breadcrumb-item"><i class="anticon anticon-home m-r-5"></i>Trang chủ</a>
            <span class="breadcrumb-item active">Chi tiết đơn hàng</span>
        </nav>
    </div>
</div>

<div class="container">
    <div class="card">
        <div class="card-body">
            <div id="invoice" class="p-h-30">
                <div class="row m-t-20 lh-2">
                    <div class="col-sm-6">
                        <h3 class="p-l-10 m-t-10">THÔNG TIN ĐƠN HÀNG:</h3>
                        <address class="p-l-10 m-t-10">
                            <p><span class="font-weight-semibold text-dark">Họ và Tên:</span> @(ViewBag.Order.CustomerName)</p>
                            <p><span class="font-weight-semibold text-dark">Địa chỉ:</span> @(ViewBag.Order.Address)</p>
                            <p><span class="font-weight-semibold text-dark">Số điện thoại:</span> @(ViewBag.Order.Phone)</p>
                            <p><span class="font-weight-semibold text-dark">Mã đơn hàng:</span> @(ViewBag.Order.OrderId)</p>
                            @if (ViewBag.Order.Status == 1)
                            {
                                <p><span class="font-weight-semibold text-dark">Trạng thái đơn hàng:</span> Chờ xác nhận </p>
                            }
                            else if (ViewBag.Order.Status == 2)
                            {
                                <p><span class="font-weight-semibold text-dark">Trạng thái đơn hàng:</span> Đã xác nhận </p>
                            }
                            else if (ViewBag.Order.Status == 3)
                            {
                                <p><span class="font-weight-semibold text-dark">Trạng thái đơn hàng:</span> Đã hủy </p>
                            }
                            else if (ViewBag.Order.Status == 4)
                            {
                                <p><span class="font-weight-semibold text-dark">Trạng thái đơn hàng:</span> Đã giao </p>
                            }
                            <p><span class="font-weight-semibold text-dark">Ngày đặt hàng:</span> @(ViewBag.Order.OrderDate)</p>
                            <p><span class="font-weight-semibold text-dark">Ghi chú:</span> @(ViewBag.Order.Note)</p>
                        </address>
                    </div>
                </div>
                <div>
                    <a class="btn btn-secondary btn-tone m-r-5" asp-area="Admin" asp-controller="AdminOrderDetails" asp-action="Create" asp-route-orderID="@(ViewBag.Order.OrderId)">
                        <i class="anticon anticon-plus-circle m-r-5"></i>
                        <span>Thêm sản phẩm</span>
                    </a>
                    <a class="btn btn-secondary btn-tone" asp-area="Admin" asp-controller="AdminOrders" asp-action="Index">
                        <i class="anticon anticon-arrow-left m-r-5"></i>
                        <span>Quay lại</span>
                    </a>
                </div>
                <div class="m-t-20">
                    <div class="table-responsive">
                        <table class="table">
                            <thead>
                                <tr>
                                    <th>Mã hóa đơn</th>
                                    <th>Tên vật phẩm</th>
                                    <th>Số lượng</th>
                                    <th>Đơn giá bán</th>
                                    <th>Giảm giá</th>
                                    <th>Thành tiền</th>
                                    <th>Thao tác</th>
                                </tr>
                            </thead>
                            <tbody>

                                @foreach (var item in Model)
                                {
                                    <tr>
                                        <th>@item.OrderId</th>
                                        <td>@item.Product.ProductName</td>
                                        <td>@item.Amount</td>
                                        <td>@item.Price.Value.ToString("#,##0 VNĐ")</td>
                                        <td>@item.Sale</td>
                                        <td>@item.Total.Value.ToString("#,##0 VNĐ")</td>
                                        <td>
                                        <td>
                                            <a asp-area="Admin" asp-controller="AdminOrderDetails" asp-action="Edit" asp-route-orderID="@item.OrderId" asp-route-productID="@item.ProductId"> <i class="anticon anticon-edit"></i></a>
                                            <a asp-area="Admin" asp-controller="AdminOrderDetails" asp-action="Delete" asp-route-orderID="@item.OrderId" asp-route-productID="@item.ProductId"><i class="anticon anticon-delete"></i></a>
                                        </td>
                                    </tr>

                                }

                            </tbody>
                        </table>
                    </div>
                    <div class="row m-t-30 lh-1-8">
                        <div class="col-sm-12">
                            <div class="float-right text-right">
                                <h3>Tổng tiền: @(ViewBag.Order.TotalOrders)</h3>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>