Market/Market/Controllers/OdersController.cs
using Market.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using System.Xml.Schema;

namespace Market.Controllers
{
    public class OdersController : Controller
    {
        private MarketContext db;
        private decimal Total = 0 ;
        public OdersController(MarketContext context)
        {
            db = context;
        }

        public string idOrder()
        {
            string idStart = "HD" + DateTime.Now.Day.ToString() + DateTime.Now.Month.ToString() + DateTime.Now.Year.ToString();
            int id = 0;
            bool check = false;
            string idOders = "";
            while (check == false)
            {
                var item = db.Orders.Find(idStart + id.ToString());
                if (item == null)
                {
                    check = true;
                }
                else
                {
                    id++;
                    check = false;
                }
            }
            idOders = idStart + id.ToString();
            return idOders;
        }

        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public IActionResult Checkout(decimal total,string id)
        {
            ViewBag.Total = total;
            ViewBag.OrderId = id;
            return View();
        }

        public IActionResult Update(decimal total)
        {
            return RedirectToAction("Checkout", new { total = total ,id = idOrder() });
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Insert([Bind("OrderId,CustomerName,Address,Phone,Note,TotalOrders")] Order oders)
        {
            oders.OrderDate = DateTime.Now.Date;
            db.Orders.Add(oders);
            db.SaveChanges();
            List<ShoppingCart> item = db.ShoppingCarts.Where(m => m.ShoppingCartId == "001").ToList();
            foreach (ShoppingCart cart in item)
            {
                OrderDetail detail = new OrderDetail();
                detail.OrderId = oders.OrderId;
                detail.ProductId = cart.ProductId;
                detail.Price = cart.Price;
                detail.Amount = cart.Amount;
                detail.Sale = 0;
                detail.Total = cart.Total;
                db.OrderDetails.Add(detail);
            }
            db.SaveChanges();
            foreach (ShoppingCart cart in item)
            {
                db.ShoppingCarts.Remove(cart);
            }
            db.SaveChanges();
            return RedirectToAction("Checkout");
        }
    }
}

Market/Market/Views/Oders/Checkout.cshtml
@{
    ViewData["Title"] = "Home Page";
    Layout = "~/Views/Shared/MyLayout.cshtml";
}

@model Order
<section class="breadcrumb-section set-bg" data-setbg="img/breadcrumb.jpg">
    <div class="container">
        <div class="row">
            <div class="col-lg-12 text-center">
                <div class="breadcrumb__text">
                    <h2>Checkout</h2>
                    <div class="breadcrumb__option">
                        <a href="./index.html">Home</a>
                        <span>Checkout</span>
                    </div>
                </div>
            </div>
        </div>
    </div>
</section>
<!-- Breadcrumb Section End -->
<!-- Checkout Section Begin -->
<section class="checkout spad">
    <div class="container">
        <div class="checkout__form">
            <h4>Hóa đơn</h4>
            <form asp-controller="Oders" asp-action="Insert" method="post">
                <div class="row">
                    <div class="col-lg-8 col-md-6">
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="checkout__input">
                                    <p>Mã hóa đơn<span>*</span></p>
                                    <label for="idInput">@ViewBag.OrderId</label>
                                    <input type="hidden" id="idInput" asp-for="OrderId" value="@ViewBag.OrderId" />
                                </div>
                            </div>
                        </div>
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="checkout__input">
                                    <p>Họ tên<span>*</span></p>
                                    <input asp-for="CustomerName" type="text">
                                </div>
                            </div>
                        </div>
                        <div class="checkout__input">
                            <p>Địa chỉ<span>*</span></p>
                            <input asp-for="Address" type="text" placeholder="Street Address" class="checkout__input__add">
                        </div>
                        <div class="row">
                            <div class="col-lg-6">
                                <div class="checkout__input">
                                    <p>Số điện thoại<span>*</span></p>
                                    <input asp-for="Phone" type="text">
                                </div>
                            </div>
                        </div>
                        <div class="checkout__input">
                            <p>Ghi chú<span>*</span></p>
                            <input asp-for="Note" type="text" placeholder="Ghi chú">
                        </div>
                    </div>
                    <div class="col-lg-4 col-md-6">
                        <div class="checkout__order">
                            <h4>Hóa đơn của bạn</h4>
                            <div class="checkout__order__total">Thành tiền <label style="margin-left:10px" for="totalInput">@ViewBag.Total</label></div>
                            <input type="hidden" id="totalInput" asp-for="TotalOrders" value="@ViewBag.Total" />
                            <button type="submit" class="site-btn">Xác nhận</button>
                        </div>
                    </div>
                </div>
            </form>
        </div>
    </div>
</section>