Market/Market/Models/Category.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;

namespace Market.Models
{
    public partial class Category
    {
        public Category()
        {
            Products = new HashSet<Product>();
        }

        [Required(ErrorMessage = "Mã danh mục không được để trống!")]
        [DisplayName("Mã danh mục")]
        public string CategoryId { get; set; } = null!;

        [Required(ErrorMessage = "Mã danh mục không được để trống!")]
        [DisplayName("Tên danh mục")]
        public string? CategoryName { get; set; }

        [Required(ErrorMessage = "Trạng thái không được để trống!")]
        [DisplayName("Trạng thái")]
        public int? Status { get; set; }
        public string StatusString
        {
            get
            {
                if (Status == 1)
                {
                    return "Đang kinh doanh";
                }
                else if (Status == 2)
                {
                    return "Ngừng kinh doanh";
                }
                return "";
            }
        }
        public virtual ICollection<Product> Products { get; set; }
    }
}

Market/Market/Areas/Admin/Controllers/CategoriesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Market.Models;
using X.PagedList;
using Market.Areas.Admin.Helpers;
using System.Security.Cryptography;

namespace Market.Areas.Admin.Controllers
{
    [Area("Admin")]
    public class CategoriesController : Controller
    {
        private readonly MarketContext _context;

        public CategoriesController(MarketContext context)
        {
            _context = context;
        }


        // GET: Admin/Categories
        private int pageSize = 3;
        [Route("Admin/Categories/Index")]
        public async Task<IActionResult> Index(int? s)
        {
            var categories = (IQueryable<Category>)_context.Categories;

            if (s != null)
            {
                categories = (IQueryable<Category>)_context.Categories.Where(c => c.Status == s);
            }
            // tính số trang 
            int pageNum = (int)Math.Ceiling(categories.Count() / (float)pageSize);

            // trả số trang về view để hiển thị nav-trang
            ViewBag.pageNum = pageNum;

            //lấy dữ liệu trang đầu
            var result = categories.Take(pageSize).ToList();

            List<SelectListItem> listStatus = CategoryStatusHelper.GetStatusList();
            ViewBag.Status = listStatus;

            return View(result);

        }
        public IActionResult CategoryFilter(int? s, string? keyword, int? pageIndex)
        {
            var categories = (IQueryable<Category>)_context.Categories;

            // lấy chỉ số trang
            int page = (int)(pageIndex == null || pageIndex <= 0 ? 1 : pageIndex);

            if (s != null && s != 0)
            {
                //lọc
                categories = categories.Where(c => c.Status == s);

                // gửi s về view để ghi lại trên nav-phân trang
                ViewBag.s = s;
            }

            if (keyword != null && keyword != "")
            {
                categories = categories.Where(x => x.CategoryId.ToLower().Contains(keyword.ToLower()) ||
                                                x.CategoryName.ToLower().Contains(keyword.ToLower()));
                ViewBag.keyword = keyword;
            }

            // tính số trang 
            int pageNum = (int)Math.Ceiling(categories.Count() / (float)pageSize);

            // gửi về view
            ViewBag.pageNum = pageNum;

            // chọn dữ liệu trong trang hiện tại 
            var result = categories.Skip(pageSize * (page - 1)).Take(pageSize);

            return PartialView("CategoryTable", result);
        }
        /*
        // GET: Admin/Categories/Details/5
        public async Task<IActionResult> Details(string id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.CategoryId == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }
        */
        // GET: Admin/Categories/Create
        public IActionResult Create()
        {
            List<SelectListItem> listStatus = CategoryStatusHelper.GetStatusList();
            ViewBag.Status = listStatus;
            return View();
        }

        // POST: Admin/Categories/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("CategoryId,CategoryName,Status")] Category category)
        {
            if (_context.Categories.Any(c => c.CategoryId == category.CategoryId))
            {
                ModelState.AddModelError("CategoryId", "Mã danh mục đã tồn tại.");

                List<SelectListItem> status = CategoryStatusHelper.GetStatusList();
                ViewBag.Status = status;
                return View(category);
            }
            if (ModelState.IsValid)
            {
                _context.Add(category);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            List<SelectListItem> listStatus = CategoryStatusHelper.GetStatusList();
            ViewBag.Status = listStatus;
            return View(category);
        }

        // GET: Admin/Categories/Edit/5
        public async Task<IActionResult> Edit(string id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var category = await _context.Categories.FindAsync(id);
            if (category == null)
            {
                return NotFound();
            }
            List<SelectListItem> listStatus = CategoryStatusHelper.GetStatusList();
            ViewBag.Status = listStatus;
            return View(category);
        }

        // POST: Admin/Categories/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(string id, [Bind("CategoryId,CategoryName,Status")] Category category)
        {
            if (id != category.CategoryId)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(category);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!CategoryExists(category.CategoryId))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            List<SelectListItem> listStatus = CategoryStatusHelper.GetStatusList();
            ViewBag.Status = listStatus;
            return View(category);
        }

        // GET: Admin/Categories/Delete/5
        public async Task<IActionResult> Delete(string id)
        {
            if (id == null || _context.Categories == null)
            {
                return NotFound();
            }

            var category = await _context.Categories
                .FirstOrDefaultAsync(m => m.CategoryId == id);
            if (category == null)
            {
                return NotFound();
            }

            return View(category);
        }

        // POST: Admin/Categories/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(string id)
        {
            if (_context.Categories == null)
            {
                return Problem("Entity set 'MarketContext.Categories'  is null.");
            }
            var category = await _context.Categories.FindAsync(id);
            if (category != null)
            {
                _context.Categories.Remove(category);
            }

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool CategoryExists(string id)
        {
            return (_context.Categories?.Any(e => e.CategoryId == id)).GetValueOrDefault();
        }
    }
}

Market/Market/Areas/Admin/Views/Categories/CategoryTable.cshtml
@model IEnumerable<Market.Models.Category>

    <div class="col-sm-12 col-md-12 col-lg-12 table-responsive">
        <table class="table table-hover e-commerce-table ">
            <thead>
                <tr class="text-center">
                    <th class="text-nowrap">Mã danh mục</th>
                    <th class="text-nowrap">Tên danh mục</th>
                    <th class="text-nowrap">Trạng thái</th>
                    <th class="text-nowrap">Chức năng</th>
                </tr>
            </thead>
            <tbody>
                @foreach (var item in Model)
                {
                    <tr class="text-center">
                        <td>
                            @item.CategoryId
                        </td>
                        <td>
                            @item.CategoryName
                        </td>
                        <td>
                            @*  @item.StatusString *@
                            @if (item.Status == 1)
                            {
                                <div>
                                    <div class="badge badge-success badge-dot m-r-10"></div>
                                    <span>Đang kinh doanh</span>
                                </div>
                            }
                            else if (item.Status == 2)
                            {
                                <div>
                                    <div class="badge badge-danger badge-dot m-r-10"></div>
                                    <span>Ngừng kinh doanh</span>
                                </div>
                            }
                        </td>

                        <td>
                            <a class="btn btn-icon btn-hover btn-sm btn-rounded pull-right" asp-area="Admin" asp-controller="Categories" asp-action="Edit" asp-route-id="@item.CategoryId"><i class="anticon anticon-edit"></i></a>
                        </td>
                    </tr>
                }
            </tbody>
        </table>

    </div>
    @* Thanh nav-phân trang *@
    <ul class="pagination m-l-20 m-t-5">
        @for (int i = 1; i <= ViewBag.pageNum; i++)
        {
            <li class="page-item active" page="@i"
            @(ViewBag.s != null ? " s='@ViewBag.s'" : "")
            @(ViewBag.keyword != null ? " keyword='@ViewBag.keyword'" : "") >
                <a class="page-link" style="border-radius: 5px;">@i</a>
            </li>
        }
    </ul>

Market/Market/Areas/Admin/Views/Categories/Create.cshtml
@model Market.Models.Category

@{
    ViewData["Title"] = "Create";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">
    <h2 class="header-title" style="font-size: 24px">Thêm danh mục</h2>

</div>

<div class="tab-content m-t-15">
    <div class="tab-pane fade show active" id="product-edit-basic">
        <div class="card">
            <div class="card-body">

                <form method="post" asp-action="Create">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <div class="form-group">
                        <label asp-for="CategoryId" class="control-label"></label>
                        <input asp-for="CategoryId" class="form-control" />
                        <span asp-validation-for="CategoryId" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="CategoryName" class="control-label"></label>
                        <input asp-for="CategoryName" class="form-control" />
                        <span asp-validation-for="CategoryName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Status" class="control-label"></label>
                        <select asp-for="Status" class="form-control" asp-items=@ViewBag.Status>
                        </select>
                        <span asp-validation-for="Status" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <a class="btn btn-default" asp-area="Admin" asp-controller="Categories" asp-action="Index">
                            <i class="anticon anticon-arrow-left"></i>
                            <span>Thoát</span>
                        </a>
                        <button type="submit" class="btn btn-success m-l-20">
                            <i class=" anticon anticon-save"></i>
                            <span>Lưu</span>
                        </button>
                        
                    </div>
                </form>

            </div>
        </div>
    </div>
    </div>


@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Market/Market/Areas/Admin/Views/Categories/Delete.cshtml
@model Market.Models.Category

@{
    ViewData["Title"] = "Delete";
}

<h1>Delete</h1>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Category</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CategoryName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CategoryName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="CategoryId" />
        <input type="submit" value="Delete" class="btn btn-danger" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

Market/Market/Areas/Admin/Views/Categories/Details.cshtml
@model Market.Models.Category

@{
    ViewData["Title"] = "Details";
}

<h1>Details</h1>

<div>
    <h4>Category</h4>
    <hr />
    <dl class="row">
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.CategoryName)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.CategoryName)
        </dd>
        <dt class = "col-sm-2">
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd class = "col-sm-10">
            @Html.DisplayFor(model => model.Status)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.CategoryId">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

Market/Market/Areas/Admin/Views/Categories/Edit.cshtml
@model Market.Models.Category

@{
    ViewData["Title"] = "Edit";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">
    <h2 class="header-title" style="font-size: 24px">Sửa danh mục</h2>

</div>

<div class="tab-content m-t-15">
    <div class="tab-pane fade show active" id="product-edit-basic">
        <div class="card">
            <div class="card-body">
                <form method="post" asp-action="Edit">
                    <div asp-validation-summary="ModelOnly" class="text-danger"></div>
                    <input type="hidden" asp-for="CategoryId" />
                    <div class="form-group">
                        <label asp-for="CategoryName" class="control-label"></label>
                        <input asp-for="CategoryName" class="form-control" />
                        <span asp-validation-for="CategoryName" class="text-danger"></span>
                    </div>
                    <div class="form-group">
                        <label asp-for="Status" class="control-label"></label>
                        <select asp-for="Status" class="form-control" asp-items="@ViewBag.Status"></select>
                        <span asp-validation-for="Status" class="text-danger"></span>
                    </div>
                    <div class="form-group">

                        <a class="btn btn-default" asp-area="Admin" asp-controller="Categories" asp-action="Index">
                            <i class="anticon anticon-arrow-left"></i>
                            <span>Thoát</span>
                        </a>
                        <button type="submit" class="btn btn-success m-l-20">
                            <i class=" anticon anticon-save"></i>
                            <span>Lưu</span>
                        </button>
                        
                    </div>
                </form>
            </div>
        </div>
    </div>
</div>


@section Scripts {
    @{
        await Html.RenderPartialAsync("_ValidationScriptsPartial");
    }
}

Market/Market/Areas/Admin/Views/Categories/Index.cshtml
@model IEnumerable<Market.Models.Category>
@{
    ViewData["Title"] = "Danh mục sản phẩm";
    Layout = "~/Areas/Admin/Views/Shared/_AdminLayout.cshtml";
}

<div class="page-header">
    <h2 class="header-title" style="font-size: 24px">Danh sách danh mục</h2>
</div>
<div class="card">
    <div class="card-body">
        <div class="row m-b-30">
            <div class="col-lg-8">
                <div class=" col-lg-5 m-b-10">
                    <select class="custom-select" id="sltStatus" name="sltStatus" asp-items="@ViewBag.Status" style="min-width: 180px;">
                        <option selected disabled>Trạng thái</option>
                        <option value="0">Tất cả</option>
                    </select>
                </div>
            </div>

            <div class=" col-lg-4 text-right">
                <a class="btn btn-primary m-l-5" asp-area="Admin" asp-controller="Categories" asp-action="Create">
                    <i class="anticon anticon-plus-circle m-r-5"></i>
                    <span>Thêm danh mục</span>
                </a>
            </div>
        </div>


        <div class="row m-b-20">
            <div class="col-sm-6">
                <div class="input-group">
                    <input id="keyword" name="keyword" type="text" class="form-control" placeholder="Tìm kiếm danh mục">
                    <button id="btnSearch" class="btn btn-primary m-l-5" type="button"><i class="anticon anticon-search"></i> Tìm kiếm</button>
                </div>
            </div>
            <div class="col-md-6">
                <button id="btnRefresh" class="btn btn-success m-r-5"><i class="anticon anticon-reload"></i> Làm mới</button>
            </div>
        </div>
    
    <div class="row" id="content">
        <div class="col-sm-12 table-responsive">
            <table class="table table-hover e-commerce-table ">
                <thead>
                    <tr class="text-center">
                        <th class="text-nowrap">Mã danh mục</th>
                        <th class="text-nowrap">Tên danh mục</th>
                        <th class="text-nowrap">Trạng thái</th>
                        <th class="text-nowrap">Chức năng</th>
                    </tr>
                </thead>
                <tbody>
                    @foreach (var item in Model)
                    {
                        <tr class="text-center">
                            <td>
                                @item.CategoryId
                            </td>
                            <td>
                                @item.CategoryName
                            </td>
                            <td>
                                @*  @item.StatusString *@
                                @if (item.Status == 1)
                                {
                                    <div>
                                        <div class="badge badge-success badge-dot m-r-10"></div>
                                        <span>Đang kinh doanh</span>
                                    </div>
                                }
                                else if (item.Status == 2)
                                {
                                    <div>
                                        <div class="badge badge-danger badge-dot m-r-10"></div>
                                        <span>Ngừng kinh doanh</span>
                                    </div>
                                }
                            </td>

                            <td>
                                <a class="btn btn-icon btn-hover btn-sm btn-rounded pull-right" asp-area="Admin" asp-controller="Categories" asp-action="Edit" asp-route-id="@item.CategoryId"><i class="anticon anticon-edit"></i></a>
                            </td>
                        </tr>
                    }
                </tbody>
            </table>

        </div>
        @* Thanh nav-phân trang *@
        <ul class="pagination m-l-20 m-t-5">
            @for (int i = 1; i <= ViewBag.pageNum; i++)
            {
                <li class="page-item active" page="@i"
                @(ViewBag.s != null ? " s='@ViewBag.s'" : "")
                @(ViewBag.keyword != null ? " keyword='@ViewBag.keyword'" : "") >
                    <a class="page-link" style="border-radius: 5px;">@i</a>
                </li>
            }
        </ul>
    </div>
    </div>
</div>
@section ScriptsCT{
    <script>
        $('body').on('click', 'li.page-item', function (e) {
            var page = $(this).attr("page");
            var s = $(this).attr("s");
            var keyword = $(this).attr("keyword");
            var data = { s: s, keyword: keyword, pageIndex: page };
            $.ajax({
                url: "CategoryFilter",
                data: data,
                success: function (response) {
                    $("div#content").html(response);
                }
            });
        });
        
        $("select#sltStatus").change(function (e) {
            var status = $("#sltStatus").val();
            var keyword = $("#keyword").val();
            var data = { s: status, keyword: keyword };
            $.ajax({
                url: "CategoryFilter",
                data: data,
                success: function (response) {
                    $("div#content").html(response);
                }
            });
        });
        $("button#btnSearch").click(function (e) {
            var status = $("#sltStatus").val();
            var keyword = $("#keyword").val();
            var data = { s: status, keyword: keyword };
            $.ajax({
                url: "CategoryFilter",
                data: data,
                success: function (response) {
                    $("div#content").html(response);
                }
            });
        });
        $("#btnRefresh").click(function () {
            window.location.href = '/Admin/Categories/Index';
        });
    </script>
}